### ISSUE TITLE
Fonts don't appear on Safari (Mac and iOS)

### ISSUE THREAD

**Issue by TypingSigns** [Slevinski/signwriting_2010_fonts#3]
Once installed (either by configuration profile, or as TrueType fonts), fonts do not appear in:

- Safari (Mac)
- iOS 13 apps (Safari/Chrome (Webkit), Notes, etc.)

They, however, do show up in Chrome on Mac.

([Using the Unicodeblock wiki list as a reference point](https://en.wikipedia.org/wiki/Sutton_SignWriting_(Unicode_block)))

**Comment by Slevinski** [comment]
Thanks for the report and opening the issue.

The configuration profile is a simple packaging of the TrueType Fonts so there shouldn't be any difference.

This is an issue with the SignWriting in Unicode 8 design.  Each symbol is defined with one to three characters.  To make this work, each of the symbols was added to the font file and them referenced via ligatures with a feature file.  The fonts were created with the [signwriting_2010_tools](https://github.com/Slevinski/signwriting_2010_tools).  You can see the Unicode 8 assignments in the source/signwriting_2010_unicode8.fea file.

Unfortunately, ligatures are a fickle thing and don't work consistently between browsers and operating systems.  Ligatures are seen as an optional enhancement and support is inconsistent.  Additionally, the Unicode Technical Committee has decided that additional SignWriting characters for structures and positioning will not be added to Unicode.  Put all together, I believe the SignWriting in Unicode 8 design is a dead end.

I'm open to new ideas and a better way to implement the font, but I am out of ideas.  I spent several months trying to get this to work better, but nothing helped.

I have created a new design called SignWriting in Unicode (SWU) as an experimental design that is not part of the Unicode standard.  It overwrites the SignWriting in Unicode 8 design and uses plane 4 for the SignWriting symbols.  The new fonts are smaller, faster, and work across browsers and operating systems.  Additionally, a two-dimensional font is planned that will leverage the SignWriting in Unicode (SWU) to create complete sign images directly from the font without needing a higher level protocol (such as SVG) for the spatial arrangement.

**Comment by Slevinski** [comment]
I'm closing the issue for now.  Reopen if you want to discuss or have ideas.

**Comment by TypingSigns** [comment]
Thank you for the reply.
For the record, I did some research and it seems that the main reason the font appears on some browsers today (Chrome), and as blank boxes in others (Safari) - is due to a change Apple made ~1 year ago regarding system fonts. (From memory, I believe they worked prior to Apple's change.) 

This can remain closed, as the original issue for this thread appears to lay on Apple's end.
